language: go
sudo: false

go:
  - "1.11.x"

env:
    - GO111MODULE=on

install: true

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test ./ntrip/... -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
